### ISSUE TITLE
Don't build  (branch master)

### ISSUE THREAD

**Issue by S1aNT** [SidhNor/SITracker#62]
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/tasks/receivers/UpdateStatusNotificationReceiver.java:32: error: cannot find symbol
import com.andrada.sitracker.ui.SiMainActivity_;
                               ^
  symbol:   class SiMainActivity_
  location: package com.andrada.sitracker.ui
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/tasks/UpdateAuthorsTask.java:28: error: cannot find symbol
import com.andrada.sitracker.contracts.SIPrefs_;
                                      ^
  symbol:   class SIPrefs_
  location: package com.andrada.sitracker.contracts
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/tasks/UpdateAuthorsTask.java:55: error: cannot find symbol
    SIPrefs_ prefs;
    ^
  symbol:   class SIPrefs_
  location: class UpdateAuthorsTask
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/tasks/ImportAuthorsTask.java:38: error: cannot find symbol
import com.andrada.sitracker.ui.ImportAuthorsActivity_;
                               ^
  symbol:   class ImportAuthorsActivity_
  location: package com.andrada.sitracker.ui
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/tasks/ImportAuthorsTask.java:39: error: cannot find symbol
import com.andrada.sitracker.ui.SiMainActivity_;
                               ^
  symbol:   class SiMainActivity_
  location: package com.andrada.sitracker.ui
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/adapters/AuthorsAdapter.java:26: error: cannot find symbol
import com.andrada.sitracker.contracts.SIPrefs_;
                                      ^
  symbol:   class SIPrefs_
  location: package com.andrada.sitracker.contracts
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/adapters/AuthorsAdapter.java:32: error: cannot find symbol
import com.andrada.sitracker.ui.components.AuthorItemView_;
                                          ^
  symbol:   class AuthorItemView_
  location: package com.andrada.sitracker.ui.components
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/adapters/AuthorsAdapter.java:64: error: cannot find symbol
    SIPrefs_ prefs;
    ^
  symbol:   class SIPrefs_
  location: class AuthorsAdapter
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/util/UpdateServiceHelper.java:26: error: cannot find symbol
import com.andrada.sitracker.contracts.SIPrefs_;
                                      ^
  symbol:   class SIPrefs_
  location: package com.andrada.sitracker.contracts
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/util/UpdateServiceHelper.java:27: error: cannot find symbol
import com.andrada.sitracker.tasks.UpdateAuthorsTask_;
                                  ^
  symbol:   class UpdateAuthorsTask_
  location: package com.andrada.sitracker.tasks
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/BaseActivity.java:51: error: cannot find symbol
import com.andrada.sitracker.ui.fragment.AuthorsFragment_;
                                        ^
  symbol:   class AuthorsFragment_
  location: package com.andrada.sitracker.ui.fragment
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/BaseActivity.java:53: error: cannot find symbol
import com.andrada.sitracker.ui.fragment.NewPublicationsFragment_;
                                        ^
  symbol:   class NewPublicationsFragment_
  location: package com.andrada.sitracker.ui.fragment
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/DirectoryChooserFragment.java:38: error: cannot find symbol
import com.andrada.sitracker.ui.components.FileFolderView_;
                                          ^
  symbol:   class FileFolderView_
  location: package com.andrada.sitracker.ui.components
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/widget/ClickItemTouchListener.java:72: error: cannot inherit from final GestureDetectorCompat
    private class ItemClickGestureDetector extends GestureDetectorCompat {
                                                   ^
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/ImportAuthorsActivity.java:44: error: cannot find symbol
import com.andrada.sitracker.tasks.ImportAuthorsTask_;
                                  ^
  symbol:   class ImportAuthorsTask_
  location: package com.andrada.sitracker.tasks
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/ImportAuthorsActivity.java:47: error: cannot find symbol
import com.andrada.sitracker.ui.components.ImportProgressView_;
                                          ^
  symbol:   class ImportProgressView_
  location: package com.andrada.sitracker.ui.components
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/SettingsActivity.java:35: error: cannot find symbol
import com.andrada.sitracker.contracts.SIPrefs_;
                                      ^
  symbol:   class SIPrefs_
  location: package com.andrada.sitracker.contracts
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/SettingsActivity.java:38: error: cannot find symbol
import com.andrada.sitracker.tasks.UpdateAuthorsTask_;
                                  ^
  symbol:   class UpdateAuthorsTask_
  location: package com.andrada.sitracker.tasks
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/SettingsActivity.java:111: error: cannot find symbol
        SIPrefs_ prefs;
        ^
  symbol:   class SIPrefs_
  location: class SettingsFragment
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/adapters/SearchResultsAdapter.java:28: error: cannot find symbol
import com.andrada.sitracker.ui.components.SearchAuthorItemView_;
                                          ^
  symbol:   class SearchAuthorItemView_
  location: package com.andrada.sitracker.ui.components
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/PublicationDetailsActivity.java:31: error: cannot find symbol
import com.andrada.sitracker.ui.fragment.PublicationInfoFragment_;
                                        ^
  symbol:   class PublicationInfoFragment_
  location: package com.andrada.sitracker.ui.fragment
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/SiMainActivity.java:33: error: cannot find symbol
import com.andrada.sitracker.contracts.SIPrefs_;
                                      ^
  symbol:   class SIPrefs_
  location: package com.andrada.sitracker.contracts
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/SiMainActivity.java:37: error: cannot find symbol
import com.andrada.sitracker.ui.fragment.AuthorsFragment_;
                                        ^
  symbol:   class AuthorsFragment_
  location: package com.andrada.sitracker.ui.fragment
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/SiMainActivity.java:64: error: cannot find symbol
    SIPrefs_ prefs;
    ^
  symbol:   class SIPrefs_
  location: class SiMainActivity
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/adapters/NewPubsAdapter.java:25: error: cannot find symbol
import com.andrada.sitracker.contracts.SIPrefs_;
                                      ^
  symbol:   class SIPrefs_
  location: package com.andrada.sitracker.contracts
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/adapters/NewPubsAdapter.java:30: error: cannot find symbol
import com.andrada.sitracker.ui.components.NewPubItemView_;
                                          ^
  symbol:   class NewPubItemView_
  location: package com.andrada.sitracker.ui.components
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/adapters/NewPubsAdapter.java:56: error: cannot find symbol
    SIPrefs_ prefs;
    ^
  symbol:   class SIPrefs_
  location: class NewPubsAdapter
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/adapters/PublicationsAdapter.java:31: error: cannot find symbol
import com.andrada.sitracker.contracts.SIPrefs_;
                                      ^
  symbol:   class SIPrefs_
  location: package com.andrada.sitracker.contracts
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/adapters/PublicationsAdapter.java:37: error: cannot find symbol
import com.andrada.sitracker.ui.components.PublicationCategoryItemView_;
                                          ^
  symbol:   class PublicationCategoryItemView_
  location: package com.andrada.sitracker.ui.components
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/adapters/PublicationsAdapter.java:39: error: cannot find symbol
import com.andrada.sitracker.ui.components.PublicationItemView_;
                                          ^
  symbol:   class PublicationItemView_
  location: package com.andrada.sitracker.ui.components
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/adapters/PublicationsAdapter.java:75: error: cannot find symbol
    SIPrefs_ prefs;
    ^
  symbol:   class SIPrefs_
  location: class PublicationsAdapter
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/adapters/PublicationsPageAdapter.java:23: error: cannot find symbol
import com.andrada.sitracker.contracts.SIPrefs_;
                                      ^
  symbol:   class SIPrefs_
  location: package com.andrada.sitracker.contracts
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/adapters/PublicationsPageAdapter.java:27: error: cannot find symbol
import com.andrada.sitracker.ui.fragment.PublicationsFragment_;
                                        ^
  symbol:   class PublicationsFragment_
  location: package com.andrada.sitracker.ui.fragment
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/adapters/PublicationsPageAdapter.java:47: error: cannot find symbol
    SIPrefs_ prefs;
    ^
  symbol:   class SIPrefs_
  location: class PublicationsPageAdapter
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/AuthorsFragment.java:51: error: cannot find symbol
import com.andrada.sitracker.tasks.UpdateAuthorsTask_;
                                  ^
  symbol:   class UpdateAuthorsTask_
  location: package com.andrada.sitracker.tasks
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/AuthorsFragment.java:54: error: cannot find symbol
import com.andrada.sitracker.ui.SearchActivity_;
                               ^
  symbol:   class SearchActivity_
  location: package com.andrada.sitracker.ui
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/PublicationInfoFragment.java:64: error: cannot find symbol
import com.andrada.sitracker.contracts.SIPrefs_;
                                      ^
  symbol:   class SIPrefs_
  location: package com.andrada.sitracker.contracts
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/PublicationInfoFragment.java:124: error: cannot find symbol
    SIPrefs_ prefs;
    ^
  symbol:   class SIPrefs_
  location: class PublicationInfoFragment
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/PublicationsFragment.java:32: error: cannot find symbol
import com.andrada.sitracker.contracts.SIPrefs_;
                                      ^
  symbol:   class SIPrefs_
  location: package com.andrada.sitracker.contracts
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/PublicationsFragment.java:38: error: cannot find symbol
import com.andrada.sitracker.ui.fragment.adapters.PublicationsAdapter_;
                                                 ^
  symbol:   class PublicationsAdapter_
  location: package com.andrada.sitracker.ui.fragment.adapters
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/PublicationsFragment.java:77: error: cannot find symbol
    SIPrefs_ prefs;
    ^
  symbol:   class SIPrefs_
  location: class PublicationsFragment
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/AboutDialog.java:23: error: cannot find symbol
import com.andrada.sitracker.ui.components.AboutDialogView_;
                                          ^
  symbol:   class AboutDialogView_
  location: package com.andrada.sitracker.ui.components
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/debug/actions/ShowAuthorsUpdatedNotificationFewAction.java:30: error: cannot find symbol
import com.andrada.sitracker.ui.SiMainActivity_;
                               ^
  symbol:   class SiMainActivity_
  location: package com.andrada.sitracker.ui
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/debug/actions/ShowAuthorsUpdatedNotificationALotAction.java:30: error: cannot find symbol
import com.andrada.sitracker.ui.SiMainActivity_;
                               ^
  symbol:   class SiMainActivity_
  location: package com.andrada.sitracker.ui
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/AuthorDetailsActivity.java:34: error: cannot find symbol
import com.andrada.sitracker.ui.fragment.PublicationsFragment_;
                                        ^
  symbol:   class PublicationsFragment_
  location: package com.andrada.sitracker.ui.fragment
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/tasks/receivers/UpdateStatusNotificationReceiver.java:91: error: cannot find symbol
        Intent resultIntent = new Intent(context, SiMainActivity_.class);
                                                  ^
  symbol:   class SiMainActivity_
  location: class UpdateStatusNotificationReceiver
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/tasks/receivers/UpdateStatusNotificationReceiver.java:98: error: cannot find symbol
        stackBuilder.addParentStack(SiMainActivity_.class);
                                    ^
  symbol:   class SiMainActivity_
  location: class UpdateStatusNotificationReceiver
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/tasks/ImportAuthorsTask.java:148: error: cannot find symbol
        Intent resultIntent = new Intent(this, ImportAuthorsActivity_.class);
                                               ^
  symbol:   class ImportAuthorsActivity_
  location: class ImportAuthorsTask
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/tasks/ImportAuthorsTask.java:155: error: cannot find symbol
        stackBuilder.addParentStack(ImportAuthorsActivity_.class);
                                    ^
  symbol:   class ImportAuthorsActivity_
  location: class ImportAuthorsTask
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/tasks/ImportAuthorsTask.java:207: error: cannot find symbol
            Intent finishIntent = SiMainActivity_.intent(this)
                                  ^
  symbol:   variable SiMainActivity_
  location: class ImportAuthorsTask
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/tasks/ImportAuthorsTask.java:217: error: cannot find symbol
            stackBuilder.addParentStack(SiMainActivity_.class);
                                        ^
  symbol:   class SiMainActivity_
  location: class ImportAuthorsTask
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/adapters/AuthorsAdapter.java:121: error: cannot find symbol
        ViewHolder vh = new ViewHolder(AuthorItemView_.build(context));
                                       ^
  symbol:   variable AuthorItemView_
  location: class AuthorsAdapter
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/util/UpdateServiceHelper.java:32: error: cannot find symbol
        Intent updateIntent = UpdateAuthorsTask_.intent(context.getApplicationContext()).get();
                              ^
  symbol:   variable UpdateAuthorsTask_
  location: class UpdateServiceHelper
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/util/UpdateServiceHelper.java:38: error: cannot find symbol
        final String updateServiceClassName = UpdateAuthorsTask_.class.getName();
                                              ^
  symbol:   class UpdateAuthorsTask_
  location: class UpdateServiceHelper
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/util/UpdateServiceHelper.java:48: error: cannot find symbol
        SIPrefs_ prefs = new SIPrefs_(context);
        ^
  symbol:   class SIPrefs_
  location: class UpdateServiceHelper
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/util/UpdateServiceHelper.java:48: error: cannot find symbol
        SIPrefs_ prefs = new SIPrefs_(context);
                             ^
  symbol:   class SIPrefs_
  location: class UpdateServiceHelper
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/util/UpdateServiceHelper.java:49: error: cannot find symbol
        Intent updateIntent = UpdateAuthorsTask_.intent(context.getApplicationContext()).get();
                              ^
  symbol:   variable UpdateAuthorsTask_
  location: class UpdateServiceHelper
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/util/UpdateServiceHelper.java:65: error: cannot find symbol
        Intent updateIntent = UpdateAuthorsTask_.intent(context.getApplicationContext()).get();
                              ^
  symbol:   variable UpdateAuthorsTask_
  location: class UpdateServiceHelper
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/BaseActivity.java:240: error: cannot find symbol
                AuthorsFragment authFrag = AuthorsFragment_.builder().build();
                                           ^
  symbol:   variable AuthorsFragment_
  location: class BaseActivity
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/BaseActivity.java:249: error: cannot find symbol
                NewPublicationsFragment newPubsFrag = NewPublicationsFragment_.builder().build();
                                                      ^
  symbol:   variable NewPublicationsFragment_
  location: class BaseActivity
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/BaseActivity.java:261: error: cannot find symbol
                ImportAuthorsActivity_.intent(this).start();
                ^
  symbol:   variable ImportAuthorsActivity_
  location: class BaseActivity
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/BaseActivity.java:264: error: cannot find symbol
                SettingsActivity_.intent(this).start();
                ^
  symbol:   variable SettingsActivity_
  location: class BaseActivity
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/DirectoryChooserFragment.java:570: error: cannot find symbol
                folderItemView = FileFolderView_.build(getContext());
                                 ^
  symbol:   variable FileFolderView_
  location: class DirectoryChooserFragment.FolderArrayAdapter
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/ImportAuthorsActivity.java:141: error: cannot find symbol
        Intent importSvc = ImportAuthorsTask_.intent(getApplicationContext()).get();
                           ^
  symbol:   variable ImportAuthorsTask_
  location: class ImportAuthorsActivity
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/ImportAuthorsActivity.java:159: error: cannot find symbol
        getApplicationContext().stopService(ImportAuthorsTask_.intent(getApplicationContext()).get());
                                            ^
  symbol:   variable ImportAuthorsTask_
  location: class ImportAuthorsActivity
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/ImportAuthorsActivity.java:180: error: cannot find symbol
        if (this.isImportServiceRunning(ImportAuthorsTask_.class)) {
                                        ^
  symbol:   class ImportAuthorsTask_
  location: class ImportAuthorsActivity
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/ImportAuthorsActivity.java:181: error: cannot find symbol
            Intent importSvc = ImportAuthorsTask_.intent(getApplicationContext()).get();
                               ^
  symbol:   variable ImportAuthorsTask_
  location: class ImportAuthorsActivity
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/ImportAuthorsActivity.java:205: error: cannot find symbol
                navigateUpOrBack(ImportAuthorsActivity.this, SiMainActivity_.class);
                                                             ^
  symbol: class SiMainActivity_
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/ImportAuthorsActivity.java:227: error: cannot find symbol
            SiMainActivity_.intent(this)
            ^
  symbol:   variable SiMainActivity_
  location: class ImportAuthorsActivity
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/ImportAuthorsActivity.java:242: error: cannot find symbol
                this.progressPanel = ImportProgressView_.build(this);
                                     ^
  symbol:   variable ImportProgressView_
  location: class ImportAuthorsActivity
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/SettingsActivity.java:63: error: package SettingsActivity_ does not exist
                    .add(R.id.container, SettingsActivity_.SettingsFragment_.builder().build())
                                                          ^
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/SettingsActivity.java:77: error: cannot find symbol
                navigateUpOrBack(SettingsActivity.this, SiMainActivity_.class);
                                                        ^
  symbol: class SiMainActivity_
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/SettingsActivity.java:172: error: cannot find symbol
            Intent intent = UpdateAuthorsTask_.intent(this.getActivity().getApplicationContext()).get();
                            ^
  symbol:   variable UpdateAuthorsTask_
  location: class SettingsFragment
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/SearchActivity.java:264: error: cannot find symbol
                                    SiMainActivity_.class)));
                                    ^
  symbol: class SiMainActivity_
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/adapters/SearchResultsAdapter.java:97: error: cannot find symbol
        return new ViewHolder(SearchAuthorItemView_.build(context));
                              ^
  symbol:   variable SearchAuthorItemView_
  location: class SearchResultsAdapter
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/PublicationDetailsActivity.java:65: error: cannot find symbol
        return PublicationInfoFragment_.builder().build();
               ^
  symbol:   variable PublicationInfoFragment_
  location: class PublicationDetailsActivity
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/SiMainActivity.java:83: error: cannot find symbol
            AuthorsFragment authFrag = AuthorsFragment_.builder().build();
                                       ^
  symbol:   variable AuthorsFragment_
  location: class SiMainActivity
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/SiMainActivity.java:124: error: cannot find symbol
                AuthorDetailsActivity_.class);
                ^
  symbol:   class AuthorDetailsActivity_
  location: class SiMainActivity
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/adapters/NewPubsAdapter.java:106: error: cannot find symbol
        return new ViewHolder(NewPubItemView_.build(context));
                              ^
  symbol:   variable NewPubItemView_
  location: class NewPubsAdapter
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/adapters/PublicationsAdapter.java:189: error: cannot find symbol
            publicationCategoryView = PublicationCategoryItemView_.build(context);
                                      ^
  symbol:   variable PublicationCategoryItemView_
  location: class PublicationsAdapter
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/adapters/PublicationsAdapter.java:207: error: cannot find symbol
            publicationItemView = PublicationItemView_.build(context);
                                  ^
  symbol:   variable PublicationItemView_
  location: class PublicationsAdapter
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/adapters/PublicationsPageAdapter.java:110: error: cannot find symbol
        return PublicationsFragment_.builder().authorName(auth.getName()).activeAuthorId(auth.getId()).build();
               ^
  symbol:   variable PublicationsFragment_
  location: class PublicationsPageAdapter
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/AuthorsFragment.java:201: error: cannot find symbol
        SearchActivity_.intent(this.getActivity()).start();
        ^
  symbol:   variable SearchActivity_
  location: class AuthorsFragment
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/AuthorsFragment.java:215: error: cannot find symbol
                Intent updateIntent = new Intent(getActivity(), UpdateAuthorsTask_.class);
                                                                ^
  symbol:   class UpdateAuthorsTask_
  location: class AuthorsFragment
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/PublicationInfoFragment.java:609: error: cannot find symbol
                dg = RatePublicationDialog_.builder()
                     ^
  symbol:   variable RatePublicationDialog_
  location: class PublicationInfoFragment
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/PublicationInfoFragment.java:615: error: cannot find symbol
                dg = RatePublicationDialog_.builder()
                     ^
  symbol:   variable RatePublicationDialog_
  location: class PublicationInfoFragment
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/PublicationsFragment.java:109: error: cannot find symbol
        ((PublicationsAdapter_) adapter).rebind(getActivity());
          ^
  symbol:   class PublicationsAdapter_
  location: class PublicationsFragment
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/fragment/AboutDialog.java:82: error: cannot find symbol
        AboutDialogView aboutBodyView = AboutDialogView_.build(getActivity());
                                        ^
  symbol:   variable AboutDialogView_
  location: class AboutDialog
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/debug/actions/ShowAuthorsUpdatedNotificationFewAction.java:59: error: cannot find symbol
        Intent resultIntent = new Intent(context, SiMainActivity_.class);
                                                  ^
  symbol:   class SiMainActivity_
  location: class ShowAuthorsUpdatedNotificationFewAction
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/debug/actions/ShowAuthorsUpdatedNotificationFewAction.java:66: error: cannot find symbol
        stackBuilder.addParentStack(SiMainActivity_.class);
                                    ^
  symbol:   class SiMainActivity_
  location: class ShowAuthorsUpdatedNotificationFewAction
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/debug/actions/ShowAuthorsUpdatedNotificationALotAction.java:72: error: cannot find symbol
        Intent resultIntent = new Intent(context, SiMainActivity_.class);
                                                  ^
  symbol:   class SiMainActivity_
  location: class ShowAuthorsUpdatedNotificationALotAction
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/debug/actions/ShowAuthorsUpdatedNotificationALotAction.java:79: error: cannot find symbol
        stackBuilder.addParentStack(SiMainActivity_.class);
                                    ^
  symbol:   class SiMainActivity_
  location: class ShowAuthorsUpdatedNotificationALotAction
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/AuthorDetailsActivity.java:71: error: cannot find symbol
                                SiMainActivity_.class)));
                                ^
  symbol: class SiMainActivity_
/home/slant/AndroidStudioProjects/SITracker/SITracker/src/main/java/com/andrada/sitracker/ui/AuthorDetailsActivity.java:86: error: cannot find symbol
            Fragment fragment = PublicationsFragment_.builder().activeAuthorId(selectedId).authorName(authorName).build();
                                ^
  symbol:   variable PublicationsFragment_
  location: class AuthorDetailsActivity
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
94 errors

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':SITracker:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 37.232 secs

**Comment by SidhNor** [comment]
Fixed in ac699cf
Please use develop (as the fix has not got to master yet)
